# Configuración global del sitio
title: Alexandro Roca
email: alexroca2191@gmail.com
description: Un lugar donde comparto mis proyectos y reflexiones sobre temas que me apasionan.
baseurl: ""
url: "https://alexrok21.github.io"
twitter_username: ""
github_username: alexrok21

# Tema y plugins
# theme: minima
plugins:
  - jekyll-feed

# Menú de navegación personalizado
nav:
  - title: Inicio
    url: /
  - title: Sobre mí
    url: /about/
  - title: Blog
    url: /blog/
  - title: Contacto
    url: /contact/

# Excluir archivos/carpetas del procesamiento
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/