# Configuración global del sitio
title: Alexandro Roca
email: alexroca2191@gmail.com
description: Un lugar donde comparto mis proyectos y reflexiones sobre temas que me apasionan.
baseurl: ""
url: "https://alexrok21.github.io"
twitter_username: tu_usuario_de_twitter
github_username: alexrok21

# Tema y plugins
plugins:
  - jekyll-feed

# Paginación (si se quiere tener paginación en el blog)
paginate: 5
paginate_path: "/blog/page:num"

# Menú de navegación personalizado
nav:
  - title: Inicio
    url: /
  - title: Sobre mí
    url: /about/
  - title: Blog
    url: /blog/
  - title: Contacto
    url: /contact/

# Excluir archivos/carpetas del procesamiento
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Para generar páginas de categorías y etiquetas
collections:
  categories:
    output: true
    permalink: /categories/:name/
  tags:
    output: true
    permalink: /tags/:name/

# Metadatos del autor (opcional)
author:
  name: Alexandro Roca
  bio: Desarrollador de software, creador de contenido, y amante de la tecnología.

  defaults:
  -
    scope:
      path: ""  # Aplica a todas las rutas
      type: posts
    values:
      layout: post  # Usa el layout 'post.html'
